-- Сидинг: категории, статьи и связь многие-ко-многим (соответствует scripts/seed.php)

USE blog;

INSERT INTO categories (name, slug, description) VALUES
('Автомобили', 'avtomobili', 'Статьи о авто'),
('Лес', 'les', 'Статьи о лесе'),
('Дом', 'dom', 'Статьи о доме'),
('Одинадцатиклассница', 'odinadcatiklassnica', 'Проверяем очень длинное название');

INSERT INTO articles (slug, image, name, description, text, view_count, published_at, created_at) VALUES
('lada-sedan', 'Images/lada-sedan.jpg', 'Лада седан', 'Баклажан', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('sluchaj-v-lesu', 'Images/sluchaj-v-lesu.jpg', 'Случай в лесу', 'Интересный случай в лесу', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('domashnee', 'Images/domashnee.jpg', 'Домашнее', 'Секреты домашнего уюта. Очень длинное описание.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('volga-na-restavratsii', 'Images/volga-na-restavratsii.jpg', 'Волга на реставрации', 'Как восстановить классику', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('moskvich-i-ego-istoriya', 'Images/moskvich-i-ego-istoriya.jpg', 'Москвич и его история', 'Легенда советского автопрома', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('griby-v-osennem-lesu', 'Images/griby-v-osennem-lesu.jpg', 'Грибы в осеннем лесу', 'Сбор и приготовление', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('progulka-po-zapovedniku', 'Images/progulka-po-zapovedniku.jpg', 'Прогулка по заповеднику', 'Маршруты и впечатления', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('ptitsy-sredney-polosy', 'Images/ptitsy-sredney-polosy.jpg', 'Птицы средней полосы', 'Наблюдение за пернатыми', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('remont-kuhni-svoimi-rukami', 'Images/remont-kuhni-svoimi-rukami.jpg', 'Ремонт кухни своими руками', 'С чего начать и что учесть', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('uyutnaya-gostinaya', 'Images/uyutnaya-gostinaya.jpg', 'Уютная гостиная', 'Идеи оформления интерьера', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('domashniy-sad-na-podokonnike', 'Images/domashniy-sad-na-podokonnike.jpg', 'Домашний сад на подоконнике', 'Зелень и травы круглый год', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('vypusknoy-vecher', 'Images/vypusknoy-vecher.jpg', 'Выпускной вечер', 'Подготовка к празднику', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('uchyoba-v-odinnadtsatom-klasse', 'Images/uchyoba-v-odinnadtsatom-klasse.jpg', 'Учёба в одиннадцатом классе', 'Советы будущим абитуриентам', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('ekzameny-bez-stressa', 'Images/ekzameny-bez-stressa.jpg', 'Экзамены без стресса', 'Как подготовиться к ЕГЭ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('zapchasti-dlya-otechestvennyh-avto', 'Images/zapchasti-dlya-otechestvennyh-avto.jpg', 'Запчасти для отечественных авто', 'Где искать и как выбирать', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('zimnyaya-rezina-i-bezopasnost', 'Images/zimnyaya-rezina-i-bezopasnost.jpg', 'Зимняя резина и безопасность', 'Выбор шин для холодного сезона', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('tropa-zdorovya', 'Images/tropa-zdorovya.jpg', 'Тропа здоровья', 'Скандинавская ходьба в лесу', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('yagody-i-varene', 'Images/yagody-i-varene.jpg', 'Ягоды и варенье', 'Рецепты из лесных даров', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('osenniy-les-i-fotosessiya', 'Images/osenniy-les-i-fotosessiya.jpg', 'Осенний лес и фотосессия', 'Лучшие места для съёмки', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('balkon-kak-zhiloe-prostranstvo', 'Images/balkon-kak-zhiloe-prostranstvo.jpg', 'Балкон как жилое пространство', 'Обустройство и утепление', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('detskaya-komnata', 'Images/detskaya-komnata.jpg', 'Детская комната', 'Планировка и мебель', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('hranenie-veschey-v-malenkoy-kvartire', 'Images/hranenie-veschey-v-malenkoy-kvartire.jpg', 'Хранение вещей в маленькой квартире', 'Практичные решения', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('shkolnaya-forma-i-stil', 'Images/shkolnaya-forma-i-stil.jpg', 'Школьная форма и стиль', 'Как выглядеть аккуратно', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('klassnyy-chas-i-traditsii', 'Images/klassnyy-chas-i-traditsii.jpg', 'Классный час и традиции', 'Идеи для сплочения класса', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('pervyy-avtomobil-v-seme', 'Images/pervyy-avtomobil-v-seme.jpg', 'Первый автомобиль в семье', 'Покупка подержанного авто', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('piknik-u-reki', 'Images/piknik-u-reki.jpg', 'Пикник у реки', 'Что взять и как организовать', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('dacha-vyhodnogo-dnya', 'Images/dacha-vyhodnogo-dnya.jpg', 'Дача выходного дня', 'Дом и участок за городом', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW()),
('posledniy-zvonok', 'Images/posledniy-zvonok.jpg', 'Последний звонок', 'Организация праздника в школе', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Culpa ut velit proident consectetur dolor consectetur elit incididunt laboris occaecat qui id mollit elit do. Reprehenderit exercitation amet irure sunt exercitation aute adipiscing nulla commodo pariatur laboris pariatur cupidatat.', 0, NOW(), NOW());

INSERT INTO article_category (article_id, category_id) VALUES
(1, 1),
(2, 2),
(2, 3),
(3, 1),
(3, 4),
(4, 1),
(5, 1),
(6, 2),
(7, 2),
(8, 2),
(9, 3),
(10, 3),
(11, 3),
(12, 4),
(13, 4),
(14, 1),
(15, 1),
(16, 2),
(17, 2),
(18, 3),
(19, 3),
(20, 4),
(21, 4),
(22, 1),
(23, 2),
(24, 3),
(25, 4),
(26, 1),
(26, 3),
(27, 2),
(27, 3),
(28, 3),
(28, 4);
